package com.wecare.app.data.source.local.greendao;

import com.wecare.app.data.entity.LocationData;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDataDaoConfig;

    private final LocationDataDao locationDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDataDaoConfig = daoConfigMap.get(LocationDataDao.class).clone();
        locationDataDaoConfig.initIdentityScope(type);

        locationDataDao = new LocationDataDao(locationDataDaoConfig, this);

        registerDao(LocationData.class, locationDataDao);
    }
    
    public void clear() {
        locationDataDaoConfig.clearIdentityScope();
    }

    public LocationDataDao getLocationDataDao() {
        return locationDataDao;
    }

}
