package com.wecare.app.data.source.local.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wecare.app.data.entity.LocationData;
import com.wecare.app.data.entity.VideoData;

import com.wecare.app.data.source.local.greendao.LocationDataDao;
import com.wecare.app.data.source.local.greendao.VideoDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDataDaoConfig;
    private final DaoConfig videoDataDaoConfig;

    private final LocationDataDao locationDataDao;
    private final VideoDataDao videoDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDataDaoConfig = daoConfigMap.get(LocationDataDao.class).clone();
        locationDataDaoConfig.initIdentityScope(type);

        videoDataDaoConfig = daoConfigMap.get(VideoDataDao.class).clone();
        videoDataDaoConfig.initIdentityScope(type);

        locationDataDao = new LocationDataDao(locationDataDaoConfig, this);
        videoDataDao = new VideoDataDao(videoDataDaoConfig, this);

        registerDao(LocationData.class, locationDataDao);
        registerDao(VideoData.class, videoDataDao);
    }
    
    public void clear() {
        locationDataDaoConfig.clearIdentityScope();
        videoDataDaoConfig.clearIdentityScope();
    }

    public LocationDataDao getLocationDataDao() {
        return locationDataDao;
    }

    public VideoDataDao getVideoDataDao() {
        return videoDataDao;
    }

}
